### ISSUE TITLE
Error while uploading

### ISSUE THREAD

**Issue by KenHV** [tskau/cobold#5]
Hi, I'm using the latest Docker image (along with self-hosted Cobalt API) and I get the following error:

```
Unhandled Error: Error: Object inputMediaUploadedDocument is missing required property mimeType
    at h (/app/node_modules/.pnpm/@mtcute+tl@183.0.0/node_modules/@mtcute/tl/binary/writer.js:4:48)
    at Object.inputMediaUploadedDocument (/app/node_modules/.pnpm/@mtcute+tl@183.0.0/node_modules/@mtcute/tl/binary/writer.js:32:425)
    at TlSerializationCounter.object (file:///app/node_modules/.pnpm/@mtcute+tl-runtime@0.15.0/node_modules/@mtcute/tl-runtime/esm/writer.js:92:30)
    at messages.editMessage (/app/node_modules/.pnpm/@mtcute+tl@183.0.0/node_modules/@mtcute/tl/binary/writer.js:1573:656)
    at TlSerializationCounter.object (file:///app/node_modules/.pnpm/@mtcute+tl-runtime@0.15.0/node_modules/@mtcute/tl-runtime/esm/writer.js:92:30)
    at TlSerializationCounter.countNeededBytes (file:///app/node_modules/.pnpm/@mtcute+tl-runtime@0.15.0/node_modules/@mtcute/tl-runtime/esm/writer.js:25:13)
    at TlBinaryWriter.serializeObject (file:///app/node_modules/.pnpm/@mtcute+tl-runtime@0.15.0/node_modules/@mtcute/tl-runtime/esm/writer.js:159:72)
    at SessionConnection.sendRpc (file:///app/node_modules/.pnpm/@mtcute+core@0.15.3/node_modules/@mtcute/core/esm/network/session-connection.js:1030:38)
    at MultiSessionConnection.sendRpc (file:///app/node_modules/.pnpm/@mtcute+core@0.15.3/node_modules/@mtcute/core/esm/network/multi-session-connection.js:184:42)
    at NetworkManager.call (file:///app/node_modules/.pnpm/@mtcute+core@0.15.3/node_modules/@mtcute/core/esm/network/network-manager.js:516:37)
```

Thanks for the bot!

**Comment by otomir23** [comment]
Can you provide some links that triggered this error for you?

**Comment by KenHV** [comment]
> Can you provide some links that triggered this error for you?

Here: https://www.youtube.com/watch?v=Ap6mufIuywc

It works with @coboldbot but not with my bot

**Comment by KenHV** [comment]
IDK what happened there, but I deleted the data folder and it started working again. Thanks!
